### ISSUE TITLE
Bring back the old method of directly placing files

### ISSUE THREAD

**Issue by HaneulCheong** [Linnest2020/Vic3-mapdata-editor#10]
## Conext
Our team is developing a total conversion mod featuring **a completely new map, different from that of vanilla**. We were using your program until [v1.0.36](https://github.com/Linnest2020/Vic3-mapdata-editor/releases/tag/v1.0.36) was released with the automatic game path detection feature.

## Current Behavior
The program can only read files from vanilla, which makes making a map from scratch using the program practically impossible.

## Expected Behavior
If relevant files are manually put in `data`, the program should use those files instead of the vanilla ones.

## Possible Solution
Please bring back the old method of directly placing files in `data` as a possible alternative to the auto detection.

**Comment by Linnest2020** [comment]
My apologies, This feature in [v1.0.36](https://github.com/Linnest2020/Vic3-mapdata-editor/releases/tag/v1.0.36) is for the beginner to fast use this editor, however I fogget the fantastic map editor's feelings.

If you have already make a output in `data/outputs`, please right click the tray icon and select "Debug", this mode can read only the file in `data/outputs`

However, most fantastic map modder would like a completely new map instead of vanilla, therefore, if you put `province.png` in `data`. In the [new branch](https://github.com/Linnest2020/Vic3-mapdata-editor/tree/1fad5f41fb3cdfcdab2a56a32ab3d291153ba989), it would use old method of directly placing files.

**Comment by Linnest2020** [comment]
In the [new branch](https://github.com/Linnest2020/Vic3-mapdata-editor/tree/1fad5f41fb3cdfcdab2a56a32ab3d291153ba989). if the province.png is placeholder, please deleted it.

**Comment by Linnest2020** [comment]
It maybe done, if there is anymore problem it will reopen
